# Buildpacks to include in builder
[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/java:7.4.1"
  version = "7.4.1"

# Order used for detection
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "7.4.1"

[lifecycle]
  version = "0.14.2"

# Stack that will be used by the builder
[stack]
id = "wolfi-stack-base"
run-image = "gcr.io/gunk-dev/wolfi-stack-base-run"
build-image = "gcr.io/gunk-dev/wolfi-stack-base-build"
